### PR TITLE
Create sas_253

### PR DESCRIPTION
**Pull request by gparameswaran-uptycs**

### CODE REVIEW

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 6       |
| Total checks passed      | 6       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 6       |
| Total checks passed      | 6       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by akhilsr-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 11       |
| Total checks passed      | 11       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 6       |
| Total checks passed      | 6       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by akhilsr-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 11       |
| Total checks passed      | 11       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 6       |
| Total checks passed      | 6       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 6       |
| Total checks passed      | 6       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by rkaira-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 11       |
| Total checks passed      | 11       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by gparameswaran-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 10       |
| Total checks passed      | 10       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by rkaira-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 11       |
| Total checks passed      | 10       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>sas_253.yaml (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/9c6a887616d0a58a7e230a9c2da28a8a144d9fb1/yamls%2Fsas_253.yaml#L1-L10">L1-L10</a> <br> &#9888; Minimize wildcard use in Roles and ClusterRoles</b></li>
</details>

**Comment by gparameswaran-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 10       |
| Total checks passed      | 9       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>sas_253.yaml (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/9c6a887616d0a58a7e230a9c2da28a8a144d9fb1/yamls%2Fsas_253.yaml#L1-L10">L1-L10</a> <br> &#9888; Minimize wildcard use in Roles and ClusterRoles</b></li>
</details>

**Pull request closed without merging**
