### PR TITLE
Create v2_k8s_1_pass.yaml

### PR DESCRIPTION
**Pull request by gparameswaran-uptycs**

### CODE REVIEW

**Comment by rkaira-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 11       |
| Total checks passed      | 10       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>v2_k8s_1_pass.yaml (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/d15241d7fb1a1be747a6648280609e8a420bf9d9/v2_k8s_1_pass.yaml#L1-L10">L1-L10</a> <br> &#9888; Minimize wildcard use in Roles and ClusterRoles</b></li>
</details>

**Comment by gparameswaran-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 10       |
| Total checks passed      | 9       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>v2_k8s_1_pass.yaml (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/d15241d7fb1a1be747a6648280609e8a420bf9d9/v2_k8s_1_pass.yaml#L1-L10">L1-L10</a> <br> &#9888; Minimize wildcard use in Roles and ClusterRoles</b></li>
</details>

**Comment by rkaira-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 13       |
| Total checks passed      | 11       |
| Total checks failed   | 2        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>v2_k8s_1_pass.yaml (2)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/43df69a764a687ffb98edd34970197d33985f4de/v2_k8s_1_pass.yaml#L11-L22">L11-L22</a> <br> &#9888; No ServiceAccount/Node should have `impersonate` permissions for groups/users/service-accounts</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/43df69a764a687ffb98edd34970197d33985f4de/v2_k8s_1_pass.yaml#L23-L28">L23-L28</a> <br> &#9888; The default namespace should not be used</b></li>
</details>

**Comment by gparameswaran-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 12       |
| Total checks passed      | 10       |
| Total checks failed   | 2        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>v2_k8s_1_pass.yaml (2)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/43df69a764a687ffb98edd34970197d33985f4de/v2_k8s_1_pass.yaml#L11-L22">L11-L22</a> <br> &#9888; No ServiceAccount/Node should have `impersonate` permissions for groups/users/service-accounts</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/43df69a764a687ffb98edd34970197d33985f4de/v2_k8s_1_pass.yaml#L23-L28">L23-L28</a> <br> &#9888; The default namespace should not be used</b></li>
</details>

**Comment by rkaira-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 11       |
| Total checks passed      | 11       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by gparameswaran-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 10       |
| Total checks passed      | 10       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by gparameswaran-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 10       |
| Total checks passed      | 10       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by rkaira-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 11       |
| Total checks passed      | 11       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Pull request closed without merging**
