### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by gparameswaran-uptycs**

### CODE REVIEW

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 24       |
| Total checks passed      | 23       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/b622c15952897f47045c6c3135f05468008f4950/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that certificate validation isn't disabled with curl</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 24       |
| Total checks passed      | 23       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/b6a0706c72b384996436363fbd9d5915f2959048/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that certificate validation isn't disabled with curl</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 24       |
| Total checks passed      | 23       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/e9ff2b8aaf220e92c928f4afb575585c1cabfb99/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that certificate validation isn't disabled with wget</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 24       |
| Total checks passed      | 24       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 24       |
| Total checks passed      | 23       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/61425960879bece1b9b2a414996c69cac4d1be46/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that certificate validation isn't disabled with the pip '--trusted-host' option</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 15       |
| Total checks passed      | 13       |
| Total checks failed   | 2        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (2)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/28f9dacf3ad91d71e15a72e1c4f117f2cf4e41c6/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that certificate validation isn't disabled with the PYTHONHTTPSVERIFY environmnet variable</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/28f9dacf3ad91d71e15a72e1c4f117f2cf4e41c6/Dockerfile#L6-L6">L6-L6</a> <br> &#9888; Ensure that certificate validation isn't disabled with the PYTHONHTTPSVERIFY environmnet variable</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 15       |
| Total checks passed      | 14       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/4182e6d97fd3ea3b67f4ff7f55c2c1bc722a9271/Dockerfile#L6-L6">L6-L6</a> <br> &#9888; Ensure that certificate validation isn't disabled with the PYTHONHTTPSVERIFY environmnet variable</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 15       |
| Total checks passed      | 13       |
| Total checks failed   | 2        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (2)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/34e6139973de2c74f51a61a5359249deda91a07f/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that certificate validation isn't disabled with the NODE_TLS_REJECT_UNAUTHORIZED environmnet variable</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/34e6139973de2c74f51a61a5359249deda91a07f/Dockerfile#L6-L6">L6-L6</a> <br> &#9888; Ensure that certificate validation isn't disabled with the NODE_TLS_REJECT_UNAUTHORIZED environmnet variable</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 58       |
| Total checks passed      | 58       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 24       |
| Total checks passed      | 23       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/567085c3aea130e4aef7c717e12a29bde780b804/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that packages with untrusted or missing signatures are not used by apk via the '--allow-untrusted' option</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 24       |
| Total checks passed      | 24       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 24       |
| Total checks passed      | 23       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/361c1d795e7f00bf9bfcd395e4940990607998e2/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that packages with untrusted or missing signatures are not used by apt-get via the '--allow-unauthenticated' option</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 58       |
| Total checks passed      | 55       |
| Total checks failed   | 3        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (3)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/ee8cf2c76ad13e4834a6bc321921fd9195400877/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that packages with untrusted or missing GPG signatures are not used by dnf, tdnf, or yum via the '--nogpgcheck' option</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/ee8cf2c76ad13e4834a6bc321921fd9195400877/Dockerfile#L6-L6">L6-L6</a> <br> &#9888; Ensure that packages with untrusted or missing GPG signatures are not used by dnf, tdnf, or yum via the '--nogpgcheck' option</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/ee8cf2c76ad13e4834a6bc321921fd9195400877/Dockerfile#L7-L7">L7-L7</a> <br> &#9888; Ensure that packages with untrusted or missing GPG signatures are not used by dnf, tdnf, or yum via the '--nogpgcheck' option</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 75       |
| Total checks passed      | 71       |
| Total checks failed   | 4        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (4)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/e34d83be2eecfc8364d7f959af06968636ad1957/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that packages with untrusted or missing signatures are not used by rpm via the '--nodigest', '--nosignature', '--noverify', or '--nofiledigest' options</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/e34d83be2eecfc8364d7f959af06968636ad1957/Dockerfile#L6-L6">L6-L6</a> <br> &#9888; Ensure that packages with untrusted or missing signatures are not used by rpm via the '--nodigest', '--nosignature', '--noverify', or '--nofiledigest' options</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/e34d83be2eecfc8364d7f959af06968636ad1957/Dockerfile#L7-L7">L7-L7</a> <br> &#9888; Ensure that packages with untrusted or missing signatures are not used by rpm via the '--nodigest', '--nosignature', '--noverify', or '--nofiledigest' options</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/e34d83be2eecfc8364d7f959af06968636ad1957/Dockerfile#L8-L8">L8-L8</a> <br> &#9888; Ensure that packages with untrusted or missing signatures are not used by rpm via the '--nodigest', '--nosignature', '--noverify', or '--nofiledigest' options</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 24       |
| Total checks passed      | 23       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/b764f20ecc9d65f01d568b29ae90ceccea9fa3a3/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that the '--force-yes' option is not used, as it disables signature validation and allows packages to be downgraded which can leave the system in a broken or inconsistent state</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 34       |
| Total checks passed      | 32       |
| Total checks failed   | 2        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (2)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/acef73fa99c67036d85f5cbe915386c348ab0033/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that certificate validation isn't disabled for npm via the 'NPM_CONFIG_STRICT_SSL' environmnet variable</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/acef73fa99c67036d85f5cbe915386c348ab0033/Dockerfile#L6-L6">L6-L6</a> <br> &#9888; Ensure that certificate validation isn't disabled for npm via the 'NPM_CONFIG_STRICT_SSL' environmnet variable</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 34       |
| Total checks passed      | 31       |
| Total checks failed   | 3        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (3)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/59b3083fe1582f7080e0f8a6d6441abf553be902/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that certificate validation isn't disabled for npm via the 'NPM_CONFIG_STRICT_SSL' environmnet variable</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/59b3083fe1582f7080e0f8a6d6441abf553be902/Dockerfile#L6-L6">L6-L6</a> <br> &#9888; Ensure that certificate validation isn't disabled for npm via the 'NPM_CONFIG_STRICT_SSL' environmnet variable</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/59b3083fe1582f7080e0f8a6d6441abf553be902/Dockerfile#L7-L8">L7-L8</a> <br> &#9888; Ensure that certificate validation isn't disabled for npm via the 'NPM_CONFIG_STRICT_SSL' environmnet variable</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 34       |
| Total checks passed      | 34       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 24       |
| Total checks passed      | 24       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 41       |
| Total checks passed      | 41       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 41       |
| Total checks passed      | 39       |
| Total checks failed   | 2        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (2)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/84002fac91b82c2587252b019aa5891c009254b6/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that certificate validation isn't disabled for npm or yarn by setting the option strict-ssl to false</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/84002fac91b82c2587252b019aa5891c009254b6/Dockerfile#L6-L6">L6-L6</a> <br> &#9888; Ensure that certificate validation isn't disabled for npm or yarn by setting the option strict-ssl to false</b></li>
</details>

**Comment by akhilsr-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 41       |
| Total checks passed      | 39       |
| Total checks failed   | 2        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (2)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/84002fac91b82c2587252b019aa5891c009254b6/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that certificate validation isn't disabled for npm or yarn by setting the option strict-ssl to false</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/84002fac91b82c2587252b019aa5891c009254b6/Dockerfile#L6-L6">L6-L6</a> <br> &#9888; Ensure that certificate validation isn't disabled for npm or yarn by setting the option strict-ssl to false</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 41       |
| Total checks passed      | 41       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by akhilsr-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 41       |
| Total checks passed      | 41       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 34       |
| Total checks passed      | 31       |
| Total checks failed   | 3        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (3)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/42b13fa0b9018c3d417f82ecb7d3acf2a957d505/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that certificate validation isn't disabled for git by setting the environment variable 'GIT_SSL_NO_VERIFY' to any value</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/42b13fa0b9018c3d417f82ecb7d3acf2a957d505/Dockerfile#L6-L6">L6-L6</a> <br> &#9888; Ensure that certificate validation isn't disabled for git by setting the environment variable 'GIT_SSL_NO_VERIFY' to any value</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/42b13fa0b9018c3d417f82ecb7d3acf2a957d505/Dockerfile#L7-L7">L7-L7</a> <br> &#9888; Ensure that certificate validation isn't disabled for git by setting the environment variable 'GIT_SSL_NO_VERIFY' to any value</b></li>
</details>

**Comment by akhilsr-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 34       |
| Total checks passed      | 31       |
| Total checks failed   | 3        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (3)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/42b13fa0b9018c3d417f82ecb7d3acf2a957d505/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that certificate validation isn't disabled for git by setting the environment variable 'GIT_SSL_NO_VERIFY' to any value</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/42b13fa0b9018c3d417f82ecb7d3acf2a957d505/Dockerfile#L6-L6">L6-L6</a> <br> &#9888; Ensure that certificate validation isn't disabled for git by setting the environment variable 'GIT_SSL_NO_VERIFY' to any value</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/42b13fa0b9018c3d417f82ecb7d3acf2a957d505/Dockerfile#L7-L7">L7-L7</a> <br> &#9888; Ensure that certificate validation isn't disabled for git by setting the environment variable 'GIT_SSL_NO_VERIFY' to any value</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 34       |
| Total checks passed      | 31       |
| Total checks failed   | 3        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (3)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/f9ad550becca14d5f43a942bb1272579179ad7a1/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that certificate validation isn't disabled for git by setting the environment variable 'GIT_SSL_NO_VERIFY' to any value</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/f9ad550becca14d5f43a942bb1272579179ad7a1/Dockerfile#L6-L6">L6-L6</a> <br> &#9888; Ensure that certificate validation isn't disabled for git by setting the environment variable 'GIT_SSL_NO_VERIFY' to any value</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/f9ad550becca14d5f43a942bb1272579179ad7a1/Dockerfile#L7-L7">L7-L7</a> <br> &#9888; Ensure that certificate validation isn't disabled for git by setting the environment variable 'GIT_SSL_NO_VERIFY' to any value</b></li>
</details>

**Comment by akhilsr-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 34       |
| Total checks passed      | 31       |
| Total checks failed   | 3        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (3)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/f9ad550becca14d5f43a942bb1272579179ad7a1/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that certificate validation isn't disabled for git by setting the environment variable 'GIT_SSL_NO_VERIFY' to any value</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/f9ad550becca14d5f43a942bb1272579179ad7a1/Dockerfile#L6-L6">L6-L6</a> <br> &#9888; Ensure that certificate validation isn't disabled for git by setting the environment variable 'GIT_SSL_NO_VERIFY' to any value</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/f9ad550becca14d5f43a942bb1272579179ad7a1/Dockerfile#L7-L7">L7-L7</a> <br> &#9888; Ensure that certificate validation isn't disabled for git by setting the environment variable 'GIT_SSL_NO_VERIFY' to any value</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 24       |
| Total checks passed      | 23       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/17aa93a6641dadd5f9a8612027fb9d945011ab1c/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that the yum and dnf package managers are not configured to disable SSL certificate validation via the 'sslverify' configuration option</b></li>
</details>

**Comment by akhilsr-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 24       |
| Total checks passed      | 23       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/17aa93a6641dadd5f9a8612027fb9d945011ab1c/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that the yum and dnf package managers are not configured to disable SSL certificate validation via the 'sslverify' configuration option</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 24       |
| Total checks passed      | 24       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by akhilsr-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 24       |
| Total checks passed      | 24       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 34       |
| Total checks passed      | 31       |
| Total checks failed   | 3        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (3)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/679fd90673123b41cd9fa57a8caaabf827efa3c0/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that certificate validation isn't disabled with pip via the 'PIP_TRUSTED_HOST' environment variable</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/679fd90673123b41cd9fa57a8caaabf827efa3c0/Dockerfile#L6-L6">L6-L6</a> <br> &#9888; Ensure that certificate validation isn't disabled with pip via the 'PIP_TRUSTED_HOST' environment variable</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/679fd90673123b41cd9fa57a8caaabf827efa3c0/Dockerfile#L7-L7">L7-L7</a> <br> &#9888; Ensure that certificate validation isn't disabled with the pip '--trusted-host' option</b></li>
</details>

**Comment by akhilsr-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 34       |
| Total checks passed      | 31       |
| Total checks failed   | 3        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (3)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/679fd90673123b41cd9fa57a8caaabf827efa3c0/Dockerfile#L5-L5">L5-L5</a> <br> &#9888; Ensure that certificate validation isn't disabled with pip via the 'PIP_TRUSTED_HOST' environment variable</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/679fd90673123b41cd9fa57a8caaabf827efa3c0/Dockerfile#L6-L6">L6-L6</a> <br> &#9888; Ensure that certificate validation isn't disabled with pip via the 'PIP_TRUSTED_HOST' environment variable</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/679fd90673123b41cd9fa57a8caaabf827efa3c0/Dockerfile#L7-L7">L7-L7</a> <br> &#9888; Ensure that certificate validation isn't disabled with the pip '--trusted-host' option</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 24       |
| Total checks passed      | 23       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/c3796413c33dadace9f4d468dc0e37b052d09cb0/Dockerfile#L5-L6">L5-L6</a> <br> &#9888; Ensure that 'chpasswd' is not used to set or remove passwords</b></li>
</details>

**Comment by akhilsr-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 24       |
| Total checks passed      | 23       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/c3796413c33dadace9f4d468dc0e37b052d09cb0/Dockerfile#L5-L6">L5-L6</a> <br> &#9888; Ensure that 'chpasswd' is not used to set or remove passwords</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 28       |
| Total checks passed      | 26       |
| Total checks failed   | 2        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (2)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/09e68a2cd59f4522ac799eca81de1a27de41ae43/Dockerfile#L1-L3">L1-L3</a> <br> &#9888; Ensure that a user for the container has been created<br> &#9888; Ensure that HEALTHCHECK instructions have been added to container images</b></li>
</details>

**Comment by akhilsr-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 28       |
| Total checks passed      | 26       |
| Total checks failed   | 2        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (2)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/09e68a2cd59f4522ac799eca81de1a27de41ae43/Dockerfile#L1-L3">L1-L3</a> <br> &#9888; Ensure that a user for the container has been created<br> &#9888; Ensure that HEALTHCHECK instructions have been added to container images</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 24       |
| Total checks passed      | 23       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/0d01a1577dea3bfad3db6797f5c483ea74b55d48/Dockerfile#L5-L6">L5-L6</a> <br> &#9888; Ensure that 'chpasswd' is not used to set or remove passwords</b></li>
</details>

**Comment by akhilsr-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 24       |
| Total checks passed      | 23       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/0d01a1577dea3bfad3db6797f5c483ea74b55d48/Dockerfile#L5-L6">L5-L6</a> <br> &#9888; Ensure that 'chpasswd' is not used to set or remove passwords</b></li>
</details>

**Pull request closed without merging**
