### PR TITLE
Create dockerfile

### PR DESCRIPTION
**Pull request by gparameswaran-uptycs**

### CODE REVIEW

**Comment by gparameswaran-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 5       |
| Total checks passed      | 1       |
| Total checks failed   | 4        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (4)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/1a56c658f48653fd848e7306d5499a6ff8d023c3/docker_check1%2FDockerfile#L1-L2">L1-L2</a> <br> &#9888; Ensure that a user for the container has been created<br> &#9888; Ensure that HEALTHCHECK instructions have been added to container images</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/1a56c658f48653fd848e7306d5499a6ff8d023c3/docker_check1%2FDockerfile#L1-L1">L1-L1</a> <br> &#9888; Ensure the base image uses a non latest version tag</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/1a56c658f48653fd848e7306d5499a6ff8d023c3/docker_check1%2FDockerfile#L2-L2">L2-L2</a> <br> &#9888; Ensure port 22 is not exposed</b></li>
</details>

**Comment by rkaira-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 5       |
| Total checks passed      | 1       |
| Total checks failed   | 4        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (4)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/1a56c658f48653fd848e7306d5499a6ff8d023c3/docker_check1%2FDockerfile#L1-L2">L1-L2</a> <br> &#9888; Ensure that a user for the container has been created<br> &#9888; Ensure that HEALTHCHECK instructions have been added to container images</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/1a56c658f48653fd848e7306d5499a6ff8d023c3/docker_check1%2FDockerfile#L1-L1">L1-L1</a> <br> &#9888; Ensure the base image uses a non latest version tag</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/1a56c658f48653fd848e7306d5499a6ff8d023c3/docker_check1%2FDockerfile#L2-L2">L2-L2</a> <br> &#9888; Ensure port 22 is not exposed</b></li>
</details>

**Comment by gparameswaran-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 123       |
| Total checks passed      | 109       |
| Total checks failed   | 14        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (14)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L13-L13">L13-L13</a> <br> &#9888; Ensure that certificate validation isn't disabled with the PYTHONHTTPSVERIFY environmnet variable</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L14-L14">L14-L14</a> <br> &#9888; Ensure that certificate validation isn't disabled with the PYTHONHTTPSVERIFY environmnet variable</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L12-L12">L12-L12</a> <br> &#9888; Ensure that certificate validation isn't disabled with the pip '--trusted-host' option</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L1-L14">L1-L14</a> <br> &#9888; Ensure that HEALTHCHECK instructions have been added to container images</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L6-L6">L6-L6</a> <br> &#9888; Ensure that LABEL maintainer is used instead of MAINTAINER (deprecated)</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L10-L10">L10-L10</a> <br> &#9888; Ensure that certificate validation isn't disabled with curl</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L11-L11">L11-L11</a> <br> &#9888; Ensure that certificate validation isn't disabled with wget</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L4-L4">L4-L4</a> <br> &#9888; Ensure that COPY is used instead of ADD in Dockerfiles</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L1-L1">L1-L1</a> <br> &#9888; Ensure the base image uses a non latest version tag</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L7-L7">L7-L7</a> <br> &#9888; Ensure that WORKDIR values are absolute paths</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L3-L3">L3-L3</a> <br> &#9888; Ensure the last USER is not root</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L2-L2">L2-L2</a> <br> &#9888; Ensure port 22 is not exposed</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L9-L9">L9-L9</a> <br> &#9888; Ensure that sudo isn't used</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L8-L8">L8-L8</a> <br> &#9888; Ensure that APT isn't used</b></li>
</details>

**Comment by rkaira-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 123       |
| Total checks passed      | 109       |
| Total checks failed   | 14        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (14)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L13-L13">L13-L13</a> <br> &#9888; Ensure that certificate validation isn't disabled with the PYTHONHTTPSVERIFY environmnet variable</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L14-L14">L14-L14</a> <br> &#9888; Ensure that certificate validation isn't disabled with the PYTHONHTTPSVERIFY environmnet variable</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L12-L12">L12-L12</a> <br> &#9888; Ensure that certificate validation isn't disabled with the pip '--trusted-host' option</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L1-L14">L1-L14</a> <br> &#9888; Ensure that HEALTHCHECK instructions have been added to container images</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L6-L6">L6-L6</a> <br> &#9888; Ensure that LABEL maintainer is used instead of MAINTAINER (deprecated)</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L10-L10">L10-L10</a> <br> &#9888; Ensure that certificate validation isn't disabled with curl</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L11-L11">L11-L11</a> <br> &#9888; Ensure that certificate validation isn't disabled with wget</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L4-L4">L4-L4</a> <br> &#9888; Ensure that COPY is used instead of ADD in Dockerfiles</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L1-L1">L1-L1</a> <br> &#9888; Ensure the base image uses a non latest version tag</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L7-L7">L7-L7</a> <br> &#9888; Ensure that WORKDIR values are absolute paths</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L3-L3">L3-L3</a> <br> &#9888; Ensure the last USER is not root</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L2-L2">L2-L2</a> <br> &#9888; Ensure port 22 is not exposed</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L9-L9">L9-L9</a> <br> &#9888; Ensure that sudo isn't used</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/fdc8c9320a96470dba7b4868d195e31bc9efabb4/docker_check1%2FDockerfile#L8-L8">L8-L8</a> <br> &#9888; Ensure that APT isn't used</b></li>
</details>

**Comment by rkaira-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 123       |
| Total checks passed      | 109       |
| Total checks failed   | 14        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>Dockerfile (14)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/0fd90632aef97887ff0b77fdfb01a98c45053100/docker_check1%2FDockerfile#L13-L13">L13-L13</a> <br> &#9888; Ensure that certificate validation isn't disabled with the PYTHONHTTPSVERIFY environmnet variable</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/0fd90632aef97887ff0b77fdfb01a98c45053100/docker_check1%2FDockerfile#L14-L14">L14-L14</a> <br> &#9888; Ensure that certificate validation isn't disabled with the PYTHONHTTPSVERIFY environmnet variable</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/0fd90632aef97887ff0b77fdfb01a98c45053100/docker_check1%2FDockerfile#L12-L12">L12-L12</a> <br> &#9888; Ensure that certificate validation isn't disabled with the pip '--trusted-host' option</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/0fd90632aef97887ff0b77fdfb01a98c45053100/docker_check1%2FDockerfile#L1-L14">L1-L14</a> <br> &#9888; Ensure that HEALTHCHECK instructions have been added to container images</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/0fd90632aef97887ff0b77fdfb01a98c45053100/docker_check1%2FDockerfile#L6-L6">L6-L6</a> <br> &#9888; Ensure that LABEL maintainer is used instead of MAINTAINER (deprecated)</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/0fd90632aef97887ff0b77fdfb01a98c45053100/docker_check1%2FDockerfile#L10-L10">L10-L10</a> <br> &#9888; Ensure that certificate validation isn't disabled with curl</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/0fd90632aef97887ff0b77fdfb01a98c45053100/docker_check1%2FDockerfile#L11-L11">L11-L11</a> <br> &#9888; Ensure that certificate validation isn't disabled with wget</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/0fd90632aef97887ff0b77fdfb01a98c45053100/docker_check1%2FDockerfile#L4-L4">L4-L4</a> <br> &#9888; Ensure that COPY is used instead of ADD in Dockerfiles</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/0fd90632aef97887ff0b77fdfb01a98c45053100/docker_check1%2FDockerfile#L1-L1">L1-L1</a> <br> &#9888; Ensure the base image uses a non latest version tag</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/0fd90632aef97887ff0b77fdfb01a98c45053100/docker_check1%2FDockerfile#L7-L7">L7-L7</a> <br> &#9888; Ensure that WORKDIR values are absolute paths</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/0fd90632aef97887ff0b77fdfb01a98c45053100/docker_check1%2FDockerfile#L3-L3">L3-L3</a> <br> &#9888; Ensure the last USER is not root</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/0fd90632aef97887ff0b77fdfb01a98c45053100/docker_check1%2FDockerfile#L2-L2">L2-L2</a> <br> &#9888; Ensure port 22 is not exposed</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/0fd90632aef97887ff0b77fdfb01a98c45053100/docker_check1%2FDockerfile#L9-L9">L9-L9</a> <br> &#9888; Ensure that sudo isn't used</b></li><br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/0fd90632aef97887ff0b77fdfb01a98c45053100/docker_check1%2FDockerfile#L8-L8">L8-L8</a> <br> &#9888; Ensure that APT isn't used</b></li>
</details>

**Pull request closed without merging**
