### PR TITLE
new pr for iac scanning kubernetes

### PR DESCRIPTION
**Pull request by gparameswaran-uptycs**
for this pr we are adding few yamls file for k8s

### CODE REVIEW

**Comment by akhilsr-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 4       |
| Total checks passed      | 2       |
| Total checks failed   | 2        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>test.yaml (2)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/1e2ba88a086fbdc729ce7cff64071386f914f1cb/test.yaml#L1-L9">L1-L9</a> <br> &#9888; The default namespace should not be used<br> &#9888; Minimize wildcard use in Roles and ClusterRoles</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 4       |
| Total checks passed      | 2       |
| Total checks failed   | 2        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>test.yaml (2)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/1e2ba88a086fbdc729ce7cff64071386f914f1cb/test.yaml#L1-L9">L1-L9</a> <br> &#9888; The default namespace should not be used<br> &#9888; Minimize wildcard use in Roles and ClusterRoles</b></li>
</details>

**Comment by akhilsr-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 11       |
| Total checks passed      | 10       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>test.yaml (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/6673df0c340a37ca09863dfe0d596493b4b6106a/test.yaml#L11-L23">L11-L23</a> <br> &#9888; No ServiceAccount/Node should have `impersonate` permissions for groups/users/service-accounts</b></li>
</details>

**Comment by kthentu-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 6       |
| Total checks passed      | 6       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by akhilsr-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 11       |
| Total checks passed      | 10       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>test.yaml (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/6673df0c340a37ca09863dfe0d596493b4b6106a/test.yaml#L11-L23">L11-L23</a> <br> &#9888; No ServiceAccount/Node should have `impersonate` permissions for groups/users/service-accounts</b></li>
</details>

**Comment by gparameswaran-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 6       |
| Total checks passed      | 6       |
| Total checks failed   | 0        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |

**Comment by gparameswaran-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 11       |
| Total checks passed      | 10       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>test.yaml (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/708c162d3efbc0fac46e29180f597d90459cf95c/test.yaml#L11-L23">L11-L23</a> <br> &#9888; No ServiceAccount/Node should have `impersonate` permissions for groups/users/service-accounts</b></li>
</details>

**Comment by rkaira-uptycs** [comment]
## Summary
| Param       | Value       |
| ----------- | ----------- |
| Total checks applied      | 11       |
| Total checks passed      | 10       |
| Total checks failed   | 1        |
| Total checks skipped   | 0        |
| Parsing errors   | 0        |
## Failed Check Details
<details>
<summary><b>test.yaml (1)</b></summary>
<br><li><b> <a href="https://github.com/DonoGHQ/k8stest/blob/708c162d3efbc0fac46e29180f597d90459cf95c/test.yaml#L11-L23">L11-L23</a> <br> &#9888; No ServiceAccount/Node should have `impersonate` permissions for groups/users/service-accounts</b></li>
</details>

**Pull request closed without merging**
